# Generated by Django 4.1.4 on 2022-12-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stranger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('imgName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_strangers',
            },
        ),
        migrations.AlterField(
            model_name='students',
            name='birthday',
            field=models.DateField(),
        ),
    ]
